name: dart_and_mysql
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  mysql1: ^0.20.0  # Add the mysql1 package here

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
